import json
import hashlib
import subprocess
import sys
from pathlib import Path
from typing import List, Dict, Any

from feniks.types import Chunk

# --- Utility Functions ---

def ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)

def sha1(s: str) -> str:
    return hashlib.sha1(s.encode("utf-8", "ignore")).hexdigest()

def extract_module_from_path(path: Path) -> str | None:
    import re
    p = path.as_posix()
    m = re.search(r"(?:^|/)app/src/([^/]+)/", p)
    return m.group(1) if m else None

# --- AST Indexer Interaction ---

def run_ast_indexer(root_path: Path, out_dir: Path) -> Path:
    """Runs the Node.js AST indexer script and returns the path to the output."""
    node_script_path = Path(__file__).parent.parent / "js_html_indexer.mjs"
    output_path = out_dir / "data" / "chunks.jsonl"
    ensure_dir(output_path.parent)

    print(f"[KB] Running AST indexer: {node_script_path}")
    cmd = [
        "node", str(node_script_path),
        "--root", str(root_path),
        "--out", str(output_path)
    ]
    try:
        # Using capture_output=True to hide the verbose output of the node script unless there's an error
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
        print(result.stdout) # Print stdout from node script
        print(f"[KB] AST indexer finished, output at: {output_path}")
        return output_path
    except subprocess.CalledProcessError as e:
        print("[KB] ERROR: AST indexer failed.", file=sys.stderr)
        print(e.stderr, file=sys.stderr)
        sys.exit(1)

# --- Chunk and Module Card Processing ---

def load_chunks_from_jsonl(path: Path) -> List[Chunk]:
    """Loads chunks from the JSONL file generated by the AST indexer."""
    chunks = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            data = json.loads(line)
            chunk_id = data.get("chunk_id") or sha1(f"{data['file_path']}:{data['start_line']}:{data['end_line']}")
            chunks.append(Chunk(
                id=chunk_id,
                file_path=data["file_path"],
                module=extract_module_from_path(Path(data["file_path"])),
                chunk_name=data["chunk_name"],
                kind="js_function" if data["file_path"].endswith(".js") else "html_section",
                ast_node_type=data["ast_node_type"],
                dependencies_di=data.get("dependencies_di", []),
                anti_patterns=[],  # Placeholder for now
                text=data["code_snippet"],
                start_line=data["start_line"],
                end_line=data["end_line"]
            ))
    return chunks

def build_module_cards_from_chunks(chunks: List[Chunk]) -> Dict[str, Any]:
    """Builds module summary cards from the list of chunks."""
    reg: Dict[str, Dict[str, set]] = {}
    for chunk in chunks:
        mkey = chunk.module or "-"
        reg.setdefault(mkey, {
            "services": set(), "controllers": set(), "factories": set(),
            "directives": set(), "routes": set(), "templates": set(), "files": set()
        })
        reg[mkey]["files"].add(chunk.file_path)

        if chunk.ast_node_type == "CallExpression":
            name = chunk.chunk_name.lower()
            if "service" in name: reg[mkey]["services"].add(chunk.chunk_name)
            elif "controller" in name: reg[mkey]["controllers"].add(chunk.chunk_name)
            elif "factory" in name: reg[mkey]["factories"].add(chunk.chunk_name)
            elif "directive" in name: reg[mkey]["directives"].add(chunk.chunk_name)
        elif chunk.ast_node_type == "NgTemplate":
            reg[mkey]["templates"].add(Path(chunk.file_path).name)

    cards = {}
    for mkey, data in reg.items():
        cards[mkey] = {k: sorted(list(v)) for k, v in data.items()}
        cards[mkey]["module"] = mkey
    return cards

def write_module_cards(out_dir: Path, modules_card: Dict[str, Any]) -> None:
    """Writes module cards and a manifest file to the output directory."""
    base = out_dir / "kb" / "modules"
    ensure_dir(base)
    for mod, data in modules_card.items():
        (base / f"{mod}.json").write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")

    manifest_path = out_dir / "kb" / "modules_manifest.json"
    manifest = {"modules": list(modules_card.keys())}
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")