import json
import subprocess
import sys
from pathlib import Path
from typing import List

from feniks.types import Chunk
from feniks.utils import sha1, extract_module_from_path, ensure_dir


from feniks.config import settings


from feniks.logger import log

def run_ast_indexer(root_path: Path) -> Path:
    """Runs the Node.js AST indexer script and returns the path to the output."""
    node_script_path = settings.NODE_INDEXER_PATH
    output_path = settings.OUTPUT_DIR / "data" / "chunks.jsonl"
    ensure_dir(output_path.parent)

    log.info(f"Running AST indexer: {node_script_path}")
    cmd = [
        "node", str(node_script_path),
        "--root", str(root_path),
        "--out", str(output_path)
    ]
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
        if result.stdout:
            log.info(result.stdout)
        log.info(f"AST indexer finished, output at: {output_path}")
        return output_path
    except subprocess.CalledProcessError as e:
        log.error("AST indexer failed.")
        log.error(e.stderr)
        raise RuntimeError("AST indexer failed.") from e


def load_chunks_from_jsonl(path: Path) -> List[Chunk]:
    """Loads chunks from the JSONL file generated by the AST indexer."""
    chunks = []
    with path.open("r", encoding="utf-8") as f:
        for i, line in enumerate(f):
            try:
                data = json.loads(line)
                chunk_id = data.get("chunk_id") or sha1(f"{data['file_path']}:{data['start_line']}:{data['end_line']}")
                chunks.append(Chunk(
                    id=chunk_id,
                    file_path=data["file_path"],
                    module=extract_module_from_path(Path(data["file_path"])),
                    chunk_name=data["chunk_name"],
                    kind="js_function" if data["file_path"].endswith(".js") else "html_section",
                    ast_node_type=data["ast_node_type"],
                    dependencies_di=data.get("dependencies_di", []),
                    anti_patterns=[],  # Placeholder for now
                    text=data["code_snippet"],
                    start_line=data["start_line"],
                    end_line=data["end_line"]
                ))
            except (json.JSONDecodeError, KeyError) as e:
                log.error(f"Could not parse line {i+1} in {path}: {e}")
                continue
    return chunks
