import sys
from pathlib import Path

core_path = str(Path(__file__).resolve().parent.parent.parent)
if core_path not in sys.path:
    sys.path.insert(0, core_path)

from feniks.core.plugins.base import LanguagePlugin, RefactorIntention, CreationSpec
from feniks.infra.logging import get_logger

logger = get_logger("plugin.php")

class PhpPlugin(LanguagePlugin):
    """
    Advanced Senior level plugin for PHP.
    Designed to integrate with nikic/php-parser for safe refactoring.
    """
    
    @property
    def name(self) -> str:
        return "php"
    
    @property
    def supported_extensions(self) -> list[str]:
        return [".php"]

    async def execute_refactor(self, code: str, intention: RefactorIntention) -> str:
        logger.info(f"Executing PHP Refactor: {intention.objective}")
        import httpx
        import os
        
        api_url = os.getenv("RAE_API_URL", "http://rae-memory:8000")
        llm_agent = os.getenv("PHOENIX_LLM_AGENT", "rae-oracle-gemini")
        project = intention.context.get("project", "default")
        impact = intention.context.get("impact_zone", {})
        
        prompt = f"""
        Jesteś RAE Phoenix (Ekspert Refaktoryzacji PHP). 
        KOD DO NAPRAWY:
        {code}
        
        POWÓD ODRZUCENIA / WYMAGANIE:
        {intention.objective}
        
        PROJEKT: {project}
        IMPACT ZONE (ZALEŻNOŚCI): {impact}
        
        Zastosuj poprawki PHP, które spełnią te wymagania. Zadbaj o standardy SOLID, czysty kod i kompatybilność z PHP 8.5.
        Zachowaj pełną funkcjonalność istniejącego kodu.
        Zwróć TYLKO I WYŁĄCZNIE poprawiony kod źródłowy PHP (bez żadnego dodatkowego tekstu, bez znaczników ```php i ```).
        """
        
        from rae_core.llm.runtime import resolve_llm_runtime
        
        try:
            provider = await resolve_llm_runtime(requirements={"requires_reasoning": True}, target_agent=llm_agent)
            fixed_code = await provider.generate(prompt)
            
            fixed_code = fixed_code.strip()
            if fixed_code.startswith("```php"):
                fixed_code = fixed_code[6:]
            if fixed_code.startswith("```"):
                fixed_code = fixed_code[3:]
            if fixed_code.endswith("```"):
                fixed_code = fixed_code[:-3]
            return fixed_code.strip()
        except Exception as e:
            logger.error(f"Error in PHP refactoring LLM call: {e}")
            return code


    async def execute_create(self, spec: CreationSpec) -> str:
        logger.info(f"Executing PHP Create: {spec.objective} at {spec.target_path}")
        return f"<?php\n// Generated by RAE-Phoenix PHP Plugin\n// Architecture: {spec.architecture_style}\n\nclass GeneratedClass {{}}\n?>"
