import sys
from pathlib import Path

core_path = str(Path(__file__).resolve().parent.parent.parent)
if core_path not in sys.path:
    sys.path.insert(0, core_path)

from feniks.core.plugins.base import LanguagePlugin, RefactorIntention, CreationSpec
from feniks.infra.logging import get_logger

logger = get_logger("plugin.typescript")

class TypeScriptPlugin(LanguagePlugin):
    """
    Advanced Senior level plugin for TS/JS/React/Next.js.
    Designed to integrate with ts-morph or jscodeshift.
    """
    
    @property
    def name(self) -> str:
        return "typescript"
    
    @property
    def supported_extensions(self) -> list[str]:
        return [".ts", ".tsx", ".js", ".jsx"]

    async def execute_refactor(self, code: str, intention: RefactorIntention) -> str:
        logger.info(f"Executing TS/JS Refactor: {intention.objective}")
        # DeepMind Architecture: Generate jscodeshift transform and execute via Node.js subprocess
        return f"// [RAE-Phoenix TS Plugin Refactored]\n{code}"

    async def execute_create(self, spec: CreationSpec) -> str:
        logger.info(f"Executing TS/JS Create: {spec.objective} at {spec.target_path}")
        return f"// Generated by RAE-Phoenix TS Plugin\n// Architecture: {spec.architecture_style}\n\nexport const GeneratedComponent = () => {{ return null; }};"
