
import argparse
import json
from pathlib import Path
import sys
from collections import defaultdict

# Add the 'scripts' directory to the Python path to allow sibling imports
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from feniks.logger import log
from feniks.config import settings

def generate_openapi_spec(ir_file: Path, output_file: Path):
    """
    Generates an OpenAPI 3.0 specification from the api_endpoints found in an IR file.
    """
    log.info(f"Generating OpenAPI spec from {ir_file}")

    # Basic OpenAPI structure
    spec = {
        "openapi": "3.0.0",
        "info": {
            "title": "Feniks Generated API",
            "version": "1.0.0",
            "description": "API specification automatically generated by Feniks from source code analysis."
        },
        "paths": defaultdict(dict)
    }

    endpoints = []
    with ir_file.open("r", encoding="utf-8") as f:
        for line in f:
            try:
                chunk = json.loads(line)
                if chunk.get("api_endpoints"):
                    endpoints.extend(chunk["api_endpoints"])
            except json.JSONDecodeError:
                log.warning(f"Skipping invalid JSON line in {ir_file}")

    if not endpoints:
        log.warning("No API endpoints found in the IR file. OpenAPI spec will be empty.")
        return

    for endpoint in endpoints:
        url = endpoint.get("url")
        method = endpoint.get("method", "get").lower()
        
        if not url:
            continue

        # Basic path parameter substitution (e.g., /api/users/{id})
        path = url.replace('${', '{').replace('}', '}')

        path_item = spec["paths"][path]

        operation = {
            "summary": f"Endpoint discovered in source code.",
            "responses": {
                "200": {
                    "description": "Successful response"
                }
            }
        }

        parameters = []
        if endpoint.get("paramKeys"):
            for param in endpoint["paramKeys"]:
                parameters.append({
                    "name": param,
                    "in": "query",
                    "schema": {"type": "string"}
                })
        
        if parameters:
            operation["parameters"] = parameters

        if method in ["post", "put", "patch"]:
            request_body = {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {key: {"type": "string"} for key in endpoint.get("dataKeys", [])}
                        }
                    }
                }
            }
            operation["requestBody"] = request_body

        path_item[method] = operation

    with output_file.open("w", encoding="utf-8") as f:
        json.dump(spec, f, indent=2)

    log.info(f"Successfully generated OpenAPI specification at {output_file}")

def main():
    parser = argparse.ArgumentParser(description="Generate OpenAPI specification from Feniks IR.")
    parser.add_argument(
        "--ir-file",
        type=Path,
        default=project_root / "runs" / "latest" / "chunks.ir.jsonl",
        help="Path to the Feniks IR JSONL file."
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=project_root / "openapi.json",
        help="Path to save the generated OpenAPI JSON file."
    )
    args = parser.parse_args()

    generate_openapi_spec(args.ir_file, args.out)

if __name__ == "__main__":
    main()
